protected/models/Campaign.php
<?php
class Campaign extends Model {

    const CAMPAIGN_PERSO_NO = 0;
    const CAMPAIGN_PERSO_YES = 1;

    protected static $_campaignPerso_map = array(
        self::CAMPAIGN_PERSO_NO => 'No',
        self::CAMPAIGN_PERSO_YES => 'Yes',
    );

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function relations() {
        return array(
            'client' => array(self::BELONGS_TO, 'Client', 'client_id'),
            'creation' => array(self::HAS_ONE, 'Creation', 'campaign_id'),
        );
    }

    public function rules() {
        return array(
            array('campaign_name, date_start, date_end, campaign_limit, personalization, accept_domain, client_id, delay', 'safe')
        );
    }

    public function checkCampaignActive() {
        $dateNow = date('Y-m-d H:i:s');
        if ($this->date_start > $dateNow || $this->date_end < $dateNow) {
            return false;
        }
        if ($this->campaign_limit < $this->sending_order) {
            return false;
        }
        return true;
    }

    public function increaseSendingOrder() {
        $this->sending_order++;
        $this->update();
    }

    /** @return CActiveDataProvider */
    public function search() {
        $criteria = new CDbCriteria;
        $criteria->compare('client_id', $this->client_id);
        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

}

protected/controllers/CampaignController.php
<?php
class CampaignController extends Controller {

    public function accessRules() {
        return array(
            array('allow',
                'actions' => array('index', 'view', 'loadHourlyStatsForCampaign', 'statsCampaign'),
                'users' => array('@'),
            ),
            array('allow',
                'actions' => array('create', 'update', 'delete'),
                'roles' => array(Login::ROLE_OPERATOR),
            ),
            array('deny',
                'users' => array('*'),
            ),
        );
    }

    public function actionView($id) {
        $this->render('view', array(
            'oCampaign' => $this->loadModel($id),
        ));
    }

    public function actionCreate() {
        $model = new Campaign;
        $this->performAjaxValidation($model);

        if (isset($_POST['Campaign'])) {
            $model->attributes = $_POST['Campaign'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->campaign_id));
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    public function actionUpdate($id) {
        $model = $this->loadModel($id);
        $this->performAjaxValidation($model);

        if (isset($_POST['Campaign'])) {
            $model->attributes = $_POST['Campaign'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->campaign_id));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    public function actionDelete($id) {
        $this->loadModel($id)->delete();

        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    public function actionIndex() {
        $oCampaign = Campaign::model();

        if (Yii::app()->user->isClient()) {
            $oCampaign->client_id = Login::getCurrentUser()->client_id;
        }
        $this->render('index', array(
            'oCampaign' => $oCampaign,
        ));
    }

    public function actionStatsCampaign($id) {
        $oCampaign = Campaign::model()->findByPk($id);

        $this->render('stats-campaign', array('oCampaign' => $oCampaign));
    }

    public function actionLoadHourlyStatsForCampaign($id) {
        $date = array();
        $c = new CDbCriteria(array('order' => 'date ASC'));
        $c->compare('campaign_id', $id);
        $c->select = array('date', 'send');
        $aCampaignStats = HourlyCampaignStat::model()->findAll($c);
        foreach ($aCampaignStats as $aCampaignStat) {
            array_push($date, array(strtotime($aCampaignStat->date) * 1000, (int) $aCampaignStat->send));
        }

        echo json_encode($date);
    }

    protected function loadModel($id) {
        if (Yii::app()->user->isClient()) {
            $model = Campaign::model()->findByAttributes(array('campaign_id' => $id, 'client_id' => Login::getCurrentUser()->client_id));
        } else {
            $model = Campaign::model()->findByPk($id);
        }
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist or you have not access.');
        return $model;
    }

    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'campaign-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/views/campaign/_campaign-code.php
<div class="span6">

    <h3>Code Init:</h3>
    <textarea class="campaign_code"><script src="<?php echo Yii::app()->params['retargetingDomain'] ?>/trackingEngine/init?clientId=1&campaignId=<?php echo $oCampaign->campaign_id; ?>"></script></textarea>
</div>
<div class="span6">

<h3>Code terminate:</h3>
<textarea class="campaign_code"><script src="<?php echo Yii::app()->params['retargetingDomain'] ?>/trackingEngine/terminate?campaignId=<?php echo $oCampaign->campaign_id; ?>"></script></textarea>
</div>

protected/views/campaign/_form.php
<?php
/* @var $this CampaignController */
/* @var $model Campaign */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'campaign-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'client_id'); ?>
		<?php echo $form->dropDownList($model, 'client_id', CHtml::listData(Client::model()->findAll(), 'client_id','client_name')) ?>
		<?php echo $form->error($model,'client_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'campaign_name'); ?>
		<?php echo $form->textField($model,'campaign_name',array('size'=>60,'maxlength'=>200)); ?>
		<?php echo $form->error($model,'campaign_name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'date_start'); ?>
		<?php echo $form->textField($model,'date_start'); ?>
		<?php echo $form->error($model,'date_start'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'date_end'); ?>
		<?php echo $form->textField($model,'date_end'); ?>
		<?php echo $form->error($model,'date_end'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'campaign_limit'); ?>
		<?php echo $form->textField($model,'campaign_limit'); ?>
		<?php echo $form->error($model,'campaign_limit'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'delay'); ?>
		<?php echo $form->textField($model,'delay'); ?>
		<?php echo $form->error($model,'delay'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'personalization'); ?>
		<?php echo $form->dropDownList($model,'personalization', Campaign::getOptions('campaignPerso')); ?>
		<?php echo $form->error($model,'personalization'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'accept_domain'); ?>
		<?php echo $form->textField($model,'accept_domain'); ?>
		<?php echo $form->error($model,'accept_domain'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/campaign/_view.php
<?php
/* @var $this CampaignController */
/* @var $data Campaign */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('campaign_id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->campaign_id), array('view', 'id'=>$data->campaign_id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('client_id')); ?>:</b>
	<?php echo CHtml::encode($data->client->client_name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('campaign_name')); ?>:</b>
	<?php echo CHtml::encode($data->campaign_name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('date_start')); ?>:</b>
	<?php echo CHtml::encode($data->date_start); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('date_end')); ?>:</b>
	<?php echo CHtml::encode($data->date_end); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('campaign_limit')); ?>:</b>
	<?php echo CHtml::encode($data->campaign_limit); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('requirement')); ?>:</b>
	<?php echo CHtml::encode($data->requirement); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('delay')); ?>:</b>
	<?php echo CHtml::encode($data->delay); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('personalization')); ?>:</b>
	<?php echo CHtml::encode($data->personalization); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('sending_order')); ?>:</b>
	<?php echo CHtml::encode($data->sending_order); ?>
	<br />

	*/ ?>

</div>

protected/views/campaign/create.php
<?php
/* @var $this CampaignController */
/* @var $model Campaign */

$this->breadcrumbs=array(
	'Campaigns'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Campaign', 'url'=>array('index')),
	array('label'=>'Manage Campaign', 'url'=>array('admin')),
);
?>

<h1>Create Campaign</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/campaign/index.php
<?php
$template = (Yii::app()->user->isOperator()) ? '{update}' : '';
$columns = array(
    array(
        'name' => 'client_name',
        'type' => 'raw',
        'value' => '$data->client->client_name',
    ),
    'campaign_name',
    'date_start',
    'date_end',
    'campaign_limit',
    'sending_order',
    array(
        'type' => 'raw',
        'value' => 'ButtonGroup::display(array(
			array(
				"text" => "Charts",
				"url" => Yii::app()->createUrl("campaign/statsCampaign",array("id"=>$data->primaryKey)),
			),array(
				"text" => "Details",
				"url" => Yii::app()->createUrl("campaign/view",array("id"=>$data->primaryKey)),
			),
		))',
        'header' => 'Options',
        'sortable' => false,
        'filter' => false,
        'htmlOptions' => array('style' => 'width:120px;'),
    ),
    array(
        'class' => 'bootstrap.widgets.TbButtonColumn',
        'updateButtonOptions' => array('class' => 'update open-ajax-box closed'),
        'template' => $template,
    )
);
?>

<div class="row-fluid">
    <div class="span12">
        <section class="utopia-widget">
            <div class="utopia-widget-title">
                <span>Campaigns</span>
            </div>
            <div class="utopia-widget-content">
                <div class="row-fluid">
                    <div class="span12">	
                        <?php
                        if (Yii::app()->user->isOperator()) {
                            $this->widget('bootstrap.widgets.TbButtonGroup', array(
                                'buttons' => array(
                                    array('label' => 'Create Campaign', 'url' => array('create')),
                                )
                            ));
                        }
                        ?>	
                        <?php
                        $this->widget('CustomTbGridView', array(
                            'dataProvider' => $oCampaign->search(),
                            'columns' => $columns,
                        ));
                        ?>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

protected/views/campaign/stats-campaign.php
<script src="http://code.highcharts.com/stock/highstock.js"></script>
<script>
    $(function () {
        $.getJSON('/campaign/loadHourlyStatsForCampaign/<?php echo $oCampaign->campaign_id; ?>', function (data) {

            // create the chart
            $('#container').highcharts('StockChart', {
                chart: {
                    alignTicks: false
                },
                rangeSelector: {
                    selected: 1
                },
                title: {
                    text: '<?php echo $oCampaign->campaign_name; ?>'
                },
                series: [{
                        type: 'column',
                        name: '<?php echo $oCampaign->campaign_name; ?>',
                        data: data,
                        dataGrouping: {
                            units: [[
                                    'week', // unit name
                                    [1] // allowed multiples
                                ], [
                                    'month',
                                    [1, 2, 3, 4, 6]
                                ]]
                        }
                    }]
            });
        });
    });
</script>

<div id="container" style="height: 400px"></div>

protected/views/campaign/update.php
<?php
/* @var $this CampaignController */
/* @var $model Campaign */

$this->breadcrumbs=array(
	'Campaigns'=>array('index'),
	$model->campaign_id=>array('view','id'=>$model->campaign_id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Campaign', 'url'=>array('index')),
	array('label'=>'Create Campaign', 'url'=>array('create')),
	array('label'=>'View Campaign', 'url'=>array('view', 'id'=>$model->campaign_id)),
	array('label'=>'Manage Campaign', 'url'=>array('admin')),
);
?>

<h1>Update Campaign <?php echo $model->campaign_id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/campaign/view.php
<section class="utopia-widget">
    <div class="utopia-widget-title">
        <span>Campaign: <?php echo $oCampaign->campaign_name; ?></span>
    </div>
    <div class="utopia-widget-content">
        <div class="row-fluid">
            <div class="span6">
                <?php
                $this->widget('bootstrap.widgets.TbDetailView', array(
                    'data' => $oCampaign,
                    'type' => 'striped condensed',
                    'attributes' => array(
                        'campaign_id',
                        array(
                            'name' => 'client_name',
                            'type' => 'raw',
                            'value' => $oCampaign->client->client_name,
                        ),
                        'campaign_name',
                        'date_start',
                        'date_end',
                    ),
                ));
                ?>
            </div>
            <div class="span6">
                <?php
                $this->widget('bootstrap.widgets.TbDetailView', array(
                    'data' => $oCampaign,
                    'type' => 'striped condensed',
                    'attributes' => array(
                        'campaign_limit',
                        'sending_order',
                        'requirement',
                        array(
                            'name' => 'delay',
                            'type' => 'raw',
                            'value' => $oCampaign->delay.' second'.(($oCampaign->delay>1)?'s':''),
                            ),
                        array(
                            'name' => 'personalization',
                            'type' => 'raw',
                            'value' => $oCampaign->getDescription("campaignPerso",$oCampaign->personalization),
                            ),
                    ),
                ));
                ?>
            </div>
        </div> 
    </div>
</section>
<section class="utopia-widget">
    <div class="utopia-widget-title">
        <span>Campaign code</span>
    </div>
    <div class="utopia-widget-content">
        <div class="row-fluid">
            <?php $this->renderPartial('_campaign-code', array('oCampaign' => $oCampaign)); ?>
        </div>
    </div>
</section>