protected/models/Client.php
<?php
class Client extends CActiveRecord {

    public function tableName() {
        return 'Client';
    }

    public function rules() {
        return array(
            array('client_name', 'required'),
            array('client_email', 'email'),
            array('client_name, client_address', 'length', 'max' => 150),
            array('client_id, client_contact_person, client_phone, client_email, client_timezone, client_country', 'length', 'max' => 100),
            array('client_id, client_name, client_contact_person, client_phone, client_email, client_timezone', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'campaigns' => array(self::HAS_MANY, 'Campaign', 'client_id'),
        );
    }

    public function attributeLabels() {
        return array(
            'client_id' => 'Client',
            'client_name' => 'Client Name',
            'client_contact_person' => 'Client Person',
            'client_phone' => 'Person Contact Phone',
            'client_email' => 'Person Contact Email',
            'client_timezone' => 'Timezone',
            'client_country' => 'Country',
            'client_address' => 'Address',
        );
    }

    /** @return CActiveDataProvider */
    public function search() {
        $criteria = new CDbCriteria;
        $criteria->compare('client_id', $this->client_id);
        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

}

protected/controllers/ClientController.php
<?php
class ClientController extends Controller {

    public function actionView($id) {
        $this->render('view', array(
            'oClient' => $this->loadModel($id),
        ));
    }

    public function actionCreate() {
        $model = new Client;

        $this->performAjaxValidation($model);

        if (isset($_POST['Client'])) {
            $model->attributes = $_POST['Client'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->client_id));
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    public function actionUpdate($id) {
        $model = $this->loadModel($id);

        $this->performAjaxValidation($model);

        if (isset($_POST['Client'])) {
            $model->attributes = $_POST['Client'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->client_id));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    public function actionDelete($id) {
        $this->loadModel($id)->delete();

        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    public function actionIndex() {
        $oClient = Client::model();
        if (Yii::app()->user->isClient()) {
            $oClient->client_id = Login::getCurrentUser()->client_id;
        }
        $this->render('index', array(
            'oClient' => $oClient,
        ));
    }

    public function loadModel($id) {
        $model = Client::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'client-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/views/client/_form.php
<?php
/* @var $this ClientController */
/* @var $model Client */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'client-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'client_name'); ?>
		<?php echo $form->textField($model,'client_name',array('size'=>60,'maxlength'=>150)); ?>
		<?php echo $form->error($model,'client_name'); ?>
	</div>
	<div class="row">
		<?php echo $form->labelEx($model,'client_contact_person'); ?>
		<?php echo $form->textField($model,'client_contact_person',array('size'=>60,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'client_contact_person'); ?>
	</div>
	<div class="row">
		<?php echo $form->labelEx($model,'client_phone'); ?>
		<?php echo $form->textField($model,'client_phone',array('size'=>60,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'client_phone'); ?>
	</div>
	<div class="row">
		<?php echo $form->labelEx($model,'client_email'); ?>
		<?php echo $form->textField($model,'client_email',array('size'=>60,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'client_email'); ?>
	</div>
	<div class="row">
		<?php echo $form->labelEx($model,'client_timezone'); ?>
		<?php echo $form->textField($model,'client_timezone',array('size'=>60,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'client_timezone'); ?>
	</div>
	<div class="row">
		<?php echo $form->labelEx($model,'client_country'); ?>
		<?php echo $form->textField($model,'client_country',array('size'=>60,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'client_country'); ?>
	</div>
	<div class="row">
		<?php echo $form->labelEx($model,'client_address'); ?>
		<?php echo $form->textField($model,'client_address',array('size'=>60,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'client_address'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/client/_view.php
<?php
/* @var $this ClientController */
/* @var $data Client */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('client_id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->client_id), array('view', 'id'=>$data->client_id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('client_name')); ?>:</b>
	<?php echo CHtml::encode($data->client_name); ?>
	<br />


</div>

protected/views/client/create.php
<?php
/* @var $this ClientController */
/* @var $model Client */

$this->breadcrumbs=array(
	'Clients'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Client', 'url'=>array('index')),
	array('label'=>'Manage Client', 'url'=>array('admin')),
);
?>

<h1>Create Client</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/client/index.php
<?php
$template = (Yii::app()->user->isOperator()) ? '{update}' : '';
$columns = array(
    'client_name',
    'client_contact_person',
    'client_phone',
    'client_email',
    'client_country',
    array(
        'type' => 'raw',
        'value' => 'ButtonGroup::display(array(
			array(
				"text" => "Details",
				"url" => Yii::app()->createUrl("client/view",array("id"=>$data->primaryKey)),
			),
		))',
        'header' => 'Options',
        'sortable' => false,
        'filter' => false,
        'htmlOptions' => array('style' => 'width:60px;'),
    ),
    array(
        'class' => 'bootstrap.widgets.TbButtonColumn',
        'updateButtonOptions' => array('class' => 'update open-ajax-box closed'),
        'template' => $template,
    )
);
?>

<div class="row-fluid">
    <div class="span12">
        <section class="utopia-widget">
            <div class="utopia-widget-title">
                <span>Clients</span>
            </div>
            <div class="utopia-widget-content">
                <div class="row-fluid">
                    <div class="span12">	
                        <?php
                        if (Yii::app()->user->isOperator()) {
                            $this->widget('bootstrap.widgets.TbButtonGroup', array(
                                'buttons' => array(
                                    array(
                                        'label' => 'Create Client',
                                        'url' => array('create'),
                                    ),
                                )
                            ));
                        }
                        ?>	
                        <?php
                        $this->widget('CustomTbGridView', array(
                            'dataProvider' => $oClient->search(),
                            'columns' => $columns,
                        ));
                        ?>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

protected/views/client/update.php
<?php
/* @var $this ClientController */
/* @var $model Client */

$this->breadcrumbs=array(
	'Clients'=>array('index'),
	$model->client_id=>array('view','id'=>$model->client_id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Client', 'url'=>array('index')),
	array('label'=>'Create Client', 'url'=>array('create')),
	array('label'=>'View Client', 'url'=>array('view', 'id'=>$model->client_id)),
	array('label'=>'Manage Client', 'url'=>array('admin')),
);
?>

<h1>Update Client <?php echo $model->client_id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/client/view.php
<section class="utopia-widget">
    <div class="utopia-widget-title">
        <span>Client: <?php echo $oClient->client_name; ?></span>
    </div>
    <div class="utopia-widget-content">
        <div class="row-fluid">
            <div class="span6">
                <?php
                $this->widget('bootstrap.widgets.TbDetailView', array(
                    'data' => $oClient,
                    'type' => 'striped condensed',
                    'attributes' => array(
                        'client_name',
                        'client_address',
                        'client_country',
                    ),
                ));
                ?>
            </div>
            <div class="span6">
                <?php
                $this->widget('bootstrap.widgets.TbDetailView', array(
                    'data' => $oClient,
                    'type' => 'striped condensed',
                    'attributes' => array(
                        'client_contact_person',
                        'client_phone',
                        'client_email',
                        'client_timezone',
                    ),
                ));
                ?>
            </div>
        </div> 
    </div>
</section>